### ISSUE TITLE
Error: The implementation of 'data' in the non-abstract

### ISSUE THREAD

**Issue by ChrisChV** [atn832/cloud_firestore_mocks#154]
When I run my tests and It throws me the following error:

```
./../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_mocks-0.8.0/lib/src/mock_query_document_snapshot.dart:5:7: Error: The implementation of 'data' in the non-abstract
class 'MockQueryDocumentSnapshot' does not conform to its interface.
class MockQueryDocumentSnapshot extends MockDocumentSnapshot
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_mocks-0.8.0/lib/src/mock_document_snapshot.dart:26:25: Context: The return type of the method
'MockDocumentSnapshot.data' is 'Map<String, dynamic>?', which does not match the return type, 'Map<String, dynamic>', of the overridden method, 'QueryDocumentSnapshot.data'.
 - 'Map' is from 'dart:core'.
Change to a subtype of 'Map<String, dynamic>'.
  Map<String, dynamic>? data() {
                        ^
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-1.0.4/lib/src/query_document_snapshot.dart:21:24: Context: This is the overridden method ('data').
  Map<String, dynamic> data() => super.data()!;
```

I am using the following packages versions:

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 1.0.3
  firebase_auth: 1.0.3
  cloud_firestore: 1.0.4
  firebase_storage: 8.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore_mocks: 0.8.0
  firebase_auth_mocks: 0.6.0
  google_sign_in_mocks: 0.2.0
```
